# Generated by Django 4.1.4 on 2022-12-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hitmen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(max_length=50, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Name"),
        ),
    ]
