# Generated by Django 4.1.4 on 2022-12-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hits",
            old_name="taget_name",
            new_name="target_name",
        ),
    ]
