# Generated by Django 4.1.4 on 2022-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hits", "0002_rename_taget_name_hits_target_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hits",
            name="creator",
            field=models.PositiveBigIntegerField(),
        ),
    ]
